name: Simple GitHub Action Demo

on:
  workflow_dispatch:   # allows manual running

jobs:
  demo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 23f2005160@ds.study.iitm.ac.in
        run: echo "Hello! This step contains my email."
